_target_: kazu.modelling.language.string_similarity_scorers.SapbertStringSimilarityScorer
sapbert: ${PLSapbertModel}
trainer:
  _target_: pytorch_lightning.Trainer
  enable_progress_bar: False
  accelerator: "cpu"
  logger: False
cache_size: 1000
