_target_: kazu.steps.ner.explosion.ExplosionNERStep
depends_on: ~
path: ${oc.env:KAZU_MODEL_PACK}/spacy_pipeline
rebuild_pipeline: False
labels:
  - gene
  - drug
  - anatomy
  - disease
  - cell_line
  - entity
parsers:
  - _target_: kazu.modelling.ontology_preprocessing.base.ChemblOntologyParser
    in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/chembl_29_sqlite/chembl_29.db
    synonym_generator: ${SynonymGeneration.chemical}
  - _target_: kazu.modelling.ontology_preprocessing.base.MondoOntologyParser
    in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/mondo.json
    synonym_generator: ${SynonymGeneration.default}
  - _target_: kazu.modelling.ontology_preprocessing.base.UberonOntologyParser
    in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/uberon.owl
    synonym_generator: ${SynonymGeneration.default}
  - _target_: kazu.modelling.ontology_preprocessing.base.MeddraOntologyParser
    in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/MedDRA 24.1
    synonym_generator: ${SynonymGeneration.default}
  - _target_: kazu.modelling.ontology_preprocessing.base.CLOOntologyParser
    in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/clo.owl
  - _target_: kazu.modelling.ontology_preprocessing.base.CellosaurusOntologyParser
    in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/cellosaurus.obo
  - _target_: kazu.modelling.ontology_preprocessing.base.OpenTargetsDiseaseOntologyParser
    in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/opentargets/diseases
    synonym_generator: ${SynonymGeneration.default}
  - _target_: kazu.modelling.ontology_preprocessing.base.OpenTargetsMoleculeOntologyParser
    in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/opentargets/molecule
    synonym_generator: ${SynonymGeneration.chemical}
  - _target_: kazu.modelling.ontology_preprocessing.base.OpenTargetsTargetOntologyParser
    in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/opentargets/targets
    synonym_generator: ${SynonymGeneration.gene}
  - _target_: kazu.modelling.ontology_preprocessing.base.BiologicalProcessGeneOntologyParser
    in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/go.owl
    synonym_generator: ${SynonymGeneration.default}
  - _target_: kazu.modelling.ontology_preprocessing.base.MolecularFunctionGeneOntologyParser
    in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/go.owl
    synonym_generator: ${SynonymGeneration.default}
  - _target_: kazu.modelling.ontology_preprocessing.base.CellularComponentGeneOntologyParser
    in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/go.owl
    synonym_generator: ${SynonymGeneration.default}
blacklisters:
  # keys are parser 'names' so we can decide what blacklister to use
  # as we loop over parsers while creating the phrase matchers
  # this should all really depend on the entity_class_to_ontology_mappings
  # part of the DictionaryEntityLinking step and use the entity class
  # to decide the blacklister.
  CHEMBL: ${BlackListers.DrugBlackLister}
  OPENTARGETS_MOLECULE: ${BlackListers.DrugBlackLister}
  MEDDRA: ${BlackListers.DiseaseBlackLister}
  MONDO: ${BlackListers.DiseaseBlackLister}
  OPENTARGETS_DISEASE: ${BlackListers.DiseaseBlackLister}
  ENSEMBL: ${BlackListers.GeneBlackLister}
  OPENTARGETS_TARGET: ${BlackListers.GeneBlackLister}
