_target_: kazu.steps.ner.explosion.ExplosionNERStep
depends_on: ~
path: ${oc.env:KAZU_MODEL_PACK}/spacy_pipeline
rebuild_pipeline: False
parsers: "${oc.dict.values: ontology_parser}"
blacklisters:
  # keys are parser 'names' so we can decide what blacklister to use
  # as we loop over parsers while creating the phrase matchers
  # this should all really depend on the entity_class_to_ontology_mappings
  # part of the DictionaryEntityLinking step and use the entity class
  # to decide the blacklister.
  CHEMBL: ${BlackListers.DrugBlackLister}
  OPENTARGETS_MOLECULE: ${BlackListers.DrugBlackLister}
  MEDDRA_DISEASE: ${BlackListers.DiseaseBlackLister}
  MONDO: ${BlackListers.DiseaseBlackLister}
  OPENTARGETS_DISEASE: ${BlackListers.DiseaseBlackLister}
  ENSEMBL: ${BlackListers.GeneBlackLister}
  OPENTARGETS_TARGET: ${BlackListers.GeneBlackLister}
entity_class_to_ontology_mappings: ${entity_class_to_ontology_map}
