_target_: kazu.steps.other.merge_overlapping_ents.MergeOverlappingEntsStep
ent_class_preferred_order:
  - disease
  - drug
  - gene
  - anatomy
  - cell_line
  - cell_type
  - go_bp
  - go_mf
  - go_cc
ent_namespace_preferred_order:
  - _target_: kazu.steps.ner.hf_token_classification.TransformersModelForTokenClassificationNerStep.namespace
  - _target_: kazu.steps.joint_ner_and_linking.explosion.ExplosionStringMatchingStep.namespace
