model:
  _target_: kazu.modelling.linking.sapbert.train.PLSapbertModel
  model_name_or_path: ${oc.env:KAZU_MODEL_PACK}/sapbert/SapBERT-from-PubMedBERT-fulltext
  sapbert_training_params:
    _target_: kazu.modelling.linking.sapbert.train.SapbertTrainingParams
    topk: 5
    lr: 2e-5
    weight_decay: 0.01
    miner_margin: 0.2
    type_of_triplets: "all"
    train_file: ???
    train_batch_size: 256
    num_workers: 2
  sapbert_evaluation_manager:
    _target_: kazu.modelling.linking.sapbert.train.SapbertEvaluationDataManager
    debug: true
    sources:
      bc5cdr-disease:
        - ???
        - ???
      mondo:
        - ???
        - ???
trainer:
  _target_: pytorch_lightning.Trainer
  progress_bar_refresh_rate: -1
  num_sanity_val_steps: 2
  gpus: 0
  accelerator: ddp
