default:
  - _target_: kazu.steps.linking.post_processing.disambiguation.strategies.DefinedElsewhereInDocumentDisambiguationStrategy
    confidence:
      _target_: kazu.data.data.DisambiguationConfidence
      _args_:
        - HIGHLY_LIKELY
  - _target_: kazu.steps.linking.post_processing.disambiguation.strategies.TfIdfDisambiguationStrategy
    confidence:
      _target_: kazu.data.data.DisambiguationConfidence
      _args_:
        - PROBABLE
    relevant_aggregation_strategies:
      - _target_: kazu.data.data.EquivalentIdAggregationStrategy
        _args_:
          - UNAMBIGUOUS
      - _target_: kazu.data.data.EquivalentIdAggregationStrategy
        _args_:
          - RESOLVED_BY_SIMILARITY
      - _target_: kazu.data.data.EquivalentIdAggregationStrategy
        _args_:
          - MERGED_AS_NON_SYMBOLIC
    scorer:
      _target_: kazu.steps.linking.post_processing.disambiguation.context_scoring.TfIdfScorer
      path:
        _target_: pathlib.Path
        _args_:
          - ${oc.env:KAZU_MODEL_PACK}/mapping_step/tfidf

gene:
  - _target_: kazu.steps.linking.post_processing.disambiguation.strategies.DefinedElsewhereInDocumentDisambiguationStrategy
    confidence:
      _target_: kazu.data.data.DisambiguationConfidence
      _args_:
        - HIGHLY_LIKELY
  - _target_: kazu.steps.linking.post_processing.disambiguation.strategies.TfIdfDisambiguationStrategy
    confidence:
      _target_: kazu.data.data.DisambiguationConfidence
      _args_:
        - PROBABLE
    relevant_aggregation_strategies:
      - _target_: kazu.data.data.EquivalentIdAggregationStrategy
        _args_:
          - CUSTOM
    scorer:
      _target_: kazu.steps.linking.post_processing.disambiguation.context_scoring.TfIdfScorer
      path:
        _target_: pathlib.Path
        _args_:
          - ${oc.env:KAZU_MODEL_PACK}/mapping_step/tfidf
  - _target_: kazu.steps.linking.post_processing.disambiguation.strategies.AnnotationLevelDisambiguationStrategy
    confidence:
      _target_: kazu.data.data.DisambiguationConfidence
      _args_:
        - POSSIBLE

cell_line:
  - _target_: kazu.steps.linking.post_processing.disambiguation.strategies.DefinedElsewhereInDocumentDisambiguationStrategy
    confidence:
      _target_: kazu.data.data.DisambiguationConfidence
      _args_:
        - HIGHLY_LIKELY
  - _target_: kazu.steps.linking.post_processing.disambiguation.strategies.TfIdfDisambiguationStrategy
    confidence: PROBABLE
    relevant_aggregation_strategies:
      - _target_: kazu.data.data.EquivalentIdAggregationStrategy
        _args_:
          - CUSTOM
    scorer:
      _target_: kazu.steps.linking.post_processing.disambiguation.context_scoring.TfIdfScorer
      path:
        _target_: pathlib.Path
        _args_:
          - ${oc.env:KAZU_MODEL_PACK}/mapping_step/tfidf
