# Used in unit tests only


# this key is used in test_PreferNearestEmbeddingToDefaultLabelDisambiguationStrategy
prefer_nearest_embedding:
  _target_: kazu.steps.linking.post_processing.disambiguation.strategies.PreferNearestEmbeddingToDefaultLabelDisambiguationStrategy
  confidence: ${confidence.disambiguation_highly_likely}
  complex_string_scorer: ${SapbertStringSimilarityScorer}
