_target_: azner.steps.ner.hf_token_classification.TransformersModelForTokenClassificationNerStep
path: ${env:KAZU_MODEL_PACK}/tinybern
depends_on: ~
batch_size: 4
stride: 16
max_sequence_length: 128
trainer:
  _target_: pytorch_lightning.Trainer
  progress_bar_refresh_rate: 0
  gpus: 0
  logger: false