_target_: kazu.steps.linking.sapbert.SapBertForEntityLinkingStep
top_n: 5
depends_on: ~
lookup_cache_size: 20000
min_string_length_to_trigger:
  drug: 5
  disease: 5
  gene: 7
  anatomy: 4
embedding_model: ${PLSapbertModel}
batch_size: 16
trainer:
  _target_: pytorch_lightning.Trainer
  enable_progress_bar: False
  accelerator: "auto"
  devices: 1
  logger: False
indices:
  - _target_: kazu.utils.link_index.MatMulTensorEmbeddingIndex
    parser: ${ontology_parser.mondo_parser}
  - _target_: kazu.utils.link_index.MatMulTensorEmbeddingIndex
    parser: ${ontology_parser.ot_disease_parser}
