_target_: kazu.steps.linking.sapbert.SapBertForEntityLinkingStep
top_n: 5
depends_on: ~
lookup_cache_size: 20000
score_cutoffs:
  - 99.9945
  - 99.9950
min_string_length_to_trigger:
  drug: 5
  disease: 5
  gene: 7
  anatomy: 4
embedding_model: ${PLSapbertModel}
batch_size: 16
trainer:
  _target_: pytorch_lightning.Trainer
  progress_bar_refresh_rate: 0
  gpus: 0
  logger: false
entity_class_to_ontology_mappings:
  drug:
    - CHEMBL
    - OPENTARGETS_MOLECULE
  disease:
    - MONDO
    - MEDDRA
    - OPENTARGETS_DISEASE
  gene:
    - OPENTARGETS_TARGET
  anatomy:
    - UBERON
indices:
  - _target_: kazu.utils.link_index.MatMulTensorEmbeddingIndex
    parser:
      _target_: kazu.modelling.ontology_preprocessing.base.MondoOntologyParser
      in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/mondo.json
      data_origin: 'MONDO-2022-04-04'
  - _target_: kazu.utils.link_index.MatMulTensorEmbeddingIndex
    parser:
      _target_: kazu.modelling.ontology_preprocessing.base.OpenTargetsDiseaseOntologyParser
      in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/opentargets/diseases
      data_origin: 'OPENTARGETS-DISEASE'
  - _target_: kazu.utils.link_index.MatMulTensorEmbeddingIndex
    parser:
      _target_: kazu.modelling.ontology_preprocessing.base.MeddraOntologyParser
      in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/MedDRA 24.1
      data_origin: 'MEDDRA-24.1'
