_target_: kazu.steps.linking.sapbert.SapBertForEntityLinkingStep
top_n: 5
depends_on: ~
lookup_cache_size: 20000
score_cutoffs:
  - 99.9945
  - 99.9950
min_string_length_to_trigger:
  drug: 5
  disease: 5
  gene: 7
  anatomy: 4
index_group:
  _target_: kazu.utils.caching.CachedIndexGroup
  entity_class_to_ontology_mappings:
    drug:
      - CHEMBL
      - OPENTARGETS_MOLECULE
    disease:
      - MONDO
      - MEDDRA
      - OPENTARGETS_DISEASE
    gene:
      - OPENTARGETS_TARGET
    anatomy:
      - UBERON
  cache_managers:
    - _target_: kazu.utils.caching.EmbeddingIndexCacheManager
      rebuild_cache: False
      model:
        _target_: kazu.modelling.linking.sapbert.train.PLSapbertModel
        model_name_or_path: ${oc.env:KAZU_MODEL_PACK}/sapbert/SapBERT-from-PubMedBERT-fulltext
      batch_size: 16
      trainer:
        _target_: pytorch_lightning.Trainer
        progress_bar_refresh_rate: 0
        gpus: 0
        logger: false
      dl_workers: 0
      ontology_partition_size: 10000
      index_type: MatMulTensorEmbeddingIndex
      parsers:
        - _target_: kazu.modelling.ontology_preprocessing.base.ChemblOntologyParser
          in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/chembl_29_sqlite/chembl_29.db
          data_origin: 'chembl_29_sqlite'
        - _target_: kazu.modelling.ontology_preprocessing.base.MondoOntologyParser
          in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/mondo.json
          data_origin: 'MONDO-2022-04-04'
        - _target_: kazu.modelling.ontology_preprocessing.base.OpenTargetsDiseaseOntologyParser
          in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/opentargets/diseases
          data_origin: 'OPENTARGETS-DISEASE'
        - _target_: kazu.modelling.ontology_preprocessing.base.OpenTargetsMoleculeOntologyParser
          in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/opentargets/molecule
          data_origin: 'OPENTARGETS-MOLECULE'
        - _target_: kazu.modelling.ontology_preprocessing.base.OpenTargetsTargetOntologyParser
          in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/opentargets/targets
          data_origin: 'OPENTARGETS-TARGET'
          min_syn_length_to_merge: 50
        - _target_: kazu.modelling.ontology_preprocessing.base.MeddraOntologyParser
          in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/MedDRA 24.1
          data_origin: 'MEDDRA-24.1'
        - _target_: kazu.modelling.ontology_preprocessing.base.UberonOntologyParser
          in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/uberon.owl
          data_origin: 'UBERON'
