_target_: kazu.pipeline.pipeline.Pipeline
steps:
  - ${ExplosionStringMatchingStep}
  - ${TransformersModelForTokenClassificationNerStep}
  - ${DictionaryEntityLinkingStep}
  - ${EntityClassDisambiguationStep}
  - ${MappingStep}
  - ${AbbreviationFinderStep}
  - ${CleanupStep}
  - ${MergeOverlappingEntsStep}
step_groups:
  ner_only:
    - _target_: kazu.steps.joint_ner_and_linking.explosion.ExplosionStringMatchingStep.namespace
    - _target_: kazu.steps.ner.hf_token_classification.TransformersModelForTokenClassificationNerStep.namespace
  linking_only:
    - _target_: kazu.steps.linking.dictionary.DictionaryEntityLinkingStep.namespace
    - _target_: kazu.steps.linking.post_processing.mapping_step.MappingStep.namespace
