_target_: kazu.pipeline.pipeline.Pipeline
steps:
  - ${ExplosionStringMatchingStep}
  - ${StanzaStep}
  - ${TransformersModelForTokenClassificationNerStep}
  - ${DictionaryEntityLinkingStep}
  - ${EntityClassDisambiguationStep}
  - ${MappingStep}
  - ${MergeOverlappingEntsStep}
  - ${AbbreviationFinderStep}
  - ${CleanupStep}
