_convert_: "all"
_target_: kazu.pipeline.Pipeline
steps:
  - ${MemoryEfficientStringMatchingStep}
  - ${TransformersModelForTokenClassificationNerStep}
  - ${DictionaryEntityLinkingStep}
  - ${RulesBasedEntityClassDisambiguationFilterStep}
  - ${MappingStep}
  - ${AbbreviationFinderStep}
  - ${CleanupStep}
  - ${MergeOverlappingEntsStep}
failure_handler:
  - _target_: kazu.pipeline.FailedDocsLogHandler
step_groups:
  ner_only:
    - _target_: kazu.steps.joint_ner_and_linking.memory_efficient_string_matching.MemoryEfficientStringMatchingStep.namespace
    - _target_: kazu.steps.ner.hf_token_classification.TransformersModelForTokenClassificationNerStep.namespace
  linking_only:
    - _target_: kazu.steps.linking.dictionary.DictionaryEntityLinkingStep.namespace
    - _target_: kazu.steps.linking.post_processing.mapping_step.MappingStep.namespace
