#note, to overcome the limitations of Omegaconf/hydra config merging, we store these as dicts
#and use (e.g.) ${oc.dict.values:..indices} where required
chembl_index:
  _target_: kazu.utils.link_index.DictionaryIndex
  parser: ${ontology_parser.chembl_parser}
  boolean_scorers: ${StringScorers.drug}

mondo_index:
  _target_: kazu.utils.link_index.DictionaryIndex
  parser: ${ontology_parser.mondo_parser}
  boolean_scorers: ${StringScorers.disease}

ot_disease_index:
  _target_: kazu.utils.link_index.DictionaryIndex
  parser: ${ontology_parser.ot_disease_parser}
  boolean_scorers: ${StringScorers.disease}

ot_molecule_index:
  _target_: kazu.utils.link_index.DictionaryIndex
  parser: ${ontology_parser.ot_molecule_parser}
  boolean_scorers: ${StringScorers.drug}

ot_target_index:
  _target_: kazu.utils.link_index.DictionaryIndex
  parser: ${ontology_parser.ot_target_parser}
  boolean_scorers: ${StringScorers.gene}

uberon_index:
  _target_: kazu.utils.link_index.DictionaryIndex
  parser: ${ontology_parser.uberon_parser}
  boolean_scorers: ${StringScorers.anatomy}

cellosaurus_index:
  _target_: kazu.utils.link_index.DictionaryIndex
  parser: ${ontology_parser.cellosaurus_parser}
  boolean_scorers: ${StringScorers.cell_type}

clo_index:
  _target_: kazu.utils.link_index.DictionaryIndex
  parser: ${ontology_parser.clo_parser}
  boolean_scorers:
    _target_: kazu.modelling.language.string_similarity_scorers.NumberMatchStringSimilarityScorer

go_bp_index:
  _target_: kazu.utils.link_index.DictionaryIndex
  parser: ${ontology_parser.go_bp_parser}
  boolean_scorers: ${StringScorers.go}

go_cc_index:
  _target_: kazu.utils.link_index.DictionaryIndex
  parser: ${ontology_parser.go_cc_parser}
  boolean_scorers: ${StringScorers.go}

go_mf_index:
  _target_: kazu.utils.link_index.DictionaryIndex
  parser: ${ontology_parser.go_mf_parser}
  boolean_scorers: ${StringScorers.go}

cl_index:
  _target_: kazu.utils.link_index.DictionaryIndex
  parser: ${ontology_parser.cl_parser}
  boolean_scorers: ${StringScorers.cell_line}
