stato_parser:
  _target_: kazu.utils.link_index.DictionaryIndex
  parser: ${ontology_parser.stato_parser}
  boolean_scorers: ${StringScorers.anatomy}  # we can just reuse the anatomy scorer here, rather than defining a new type
