defaults:
  - ray: cluster
  - TransformersModelForTokenClassificationNerStep: default
  - SapBertForEntityLinkingStep: default
  - DictionaryEntityLinkingStep: default
  - SapBertTraining: default
  - pipeline: default