_target_: azner.steps.linking.sapbert.SapBertForEntityLinkingStep
model_path: ~
knowledgebase_path: ~
batch_size: 4
process_all_entities: False
rebuild_kb_cache: False
depends_on: ~
lookup_cache_size: 5000
trainer:
  _target_: pytorch_lightning.Trainer
  progress_bar_refresh_rate: 0
  gpus: 0
