_target_: azner.steps.linking.sapbert.SapBertForEntityLinkingStep
model:
  _target_: azner.steps.linking.sapbert.PLSapbertModel
  model_name_or_path: cambridgeltl/SapBERT-from-PubMedBERT-fulltext
ontology_path: ~
batch_size: 4
process_all_entities: False
rebuild_ontology_cache: False
depends_on: ~
lookup_cache_size: 5000
dl_workers: 1
ontology_partition_size: 100000
entity_class_to_ontology_mappings:
  Drug: CHEMBL
  Disease: MONDO
  Gene: ENSEMBL
  Anatomy: UBERON
trainer:
  _target_: pytorch_lightning.Trainer
  progress_bar_refresh_rate: 0
  gpus: 0
embedding_index_factory:
  _target_: azner.steps.utils.embedding_index.EmbeddingIndexFactory
  embedding_index_class_name: MatMulTensorEmbeddingIndex
  return_n_nearest_neighbours: 5