texts:
  [
    "LncRNA MIR4435-2HG has been shown to have an oncogenic role in ovarian cancer by upregulating CDK14 and downregulating miR-128-3p, while LINC00319 down-regulated miR-423-5p and upregulated NACC1 expression, promoting cell proliferation, migration, and invasion [146, 147].",
    "The epidermal growth factor receptor (EGFR; ErbB-1; HER1 in humans) is a transmembrane protein that is a receptor for members of the epidermal growth factor family (EGF family) of extracellular protein ligands.[5]",
  ]
label_list:
  [
    "O",
    "anatomical part or tissue",
    "biological process",
    "cell type",
    "cellular component",
    "chemical",
    "disease, disorder, phenotype or trait",
    "drug",
    "gene or gene product",
    "instrument",
    "measurement",
    "method",
    "mutation",
    "organization",
    "place",
    "protein domain or region",
    "species",
    "treatment",
  ]
prediction_config:
  _target_: kazu.training.config.PredictionConfig
  path: training/models/biomedNLP_1
  batch_size: 1
  stride: 64
  max_sequence_length: 512
  device: cpu
  architecture: bert
css_colors:
  - "#000000" # Black
  - "#FF0000" # Red
  - "#00FF00" # Lime
  - "#0000FF" # Blue
  - "#FFFF00" # Yellow
  - "#00FFFF" # Cyan
  - "#FF00FF" # Magenta
  - "#800000" # Maroon
  - "#808000" # Olive
  - "#008000" # Green
  - "#800080" # Purple
  - "#008080" # Teal
  - "#FFA500" # Orange
  - "#A52A2A" # Brown
  - "#8A2BE2" # BlueViolet
  - "#5F9EA0" # CadetBlue
  - "#D2691E" # Chocolate
  - "#000080" # Navy
  - "#FFDAB9" # PeachPuff
label_studio_manager:
  _target_: kazu.annotation.label_studio.LabelStudioManager
  project_name: "clean_data"
  headers:
    Authorization: ~
