_target_: kazu.steps.linking.dictionary.DictionaryEntityLinkingStep
depends_on: ~
lookup_cache_size: 50000
top_n: 20
entity_class_to_ontology_mappings: ${..entity_class_to_ontology_map}
indices:
  - _target_: kazu.utils.link_index.DictionaryIndex
    parser: ${ontology_parser.chembl_parser}
    boolean_scorers:
      - _target_: kazu.modelling.language.string_similarity_scorers.NumberMatchStringSimilarityScorer
  - _target_: kazu.utils.link_index.DictionaryIndex
    parser: ${ontology_parser.mondo_parser}
    boolean_scorers:
      - _target_: kazu.modelling.language.string_similarity_scorers.NumberMatchStringSimilarityScorer
      - _target_: kazu.modelling.language.string_similarity_scorers.EntitySubtypeStringSimilarityScorer
  - _target_: kazu.utils.link_index.DictionaryIndex
    parser: ${ontology_parser.ot_disease_parser}
    boolean_scorers:
      - _target_: kazu.modelling.language.string_similarity_scorers.NumberMatchStringSimilarityScorer
      - _target_: kazu.modelling.language.string_similarity_scorers.EntitySubtypeStringSimilarityScorer
  - _target_: kazu.utils.link_index.DictionaryIndex
    parser: ${ontology_parser.ot_molecule_parser}
    boolean_scorers:
      - _target_: kazu.modelling.language.string_similarity_scorers.NumberMatchStringSimilarityScorer
  - _target_: kazu.utils.link_index.DictionaryIndex
    parser: ${ontology_parser.ot_target_parser}
    boolean_scorers:
      - _target_: kazu.modelling.language.string_similarity_scorers.NumberMatchStringSimilarityScorer
      - _target_: kazu.modelling.language.string_similarity_scorers.EntityNounModifierStringSimilarityScorer
      - _target_: kazu.modelling.language.string_similarity_scorers.EntitySubtypeStringSimilarityScorer
  - _target_: kazu.utils.link_index.DictionaryIndex
    parser: ${ontology_parser.meddra_parser}
    boolean_scorers:
      - _target_: kazu.modelling.language.string_similarity_scorers.NumberMatchStringSimilarityScorer
      - _target_: kazu.modelling.language.string_similarity_scorers.EntitySubtypeStringSimilarityScorer
  - _target_: kazu.utils.link_index.DictionaryIndex
    parser: ${ontology_parser.uberon_parser}
    boolean_scorers:
      - _target_: kazu.modelling.language.string_similarity_scorers.NumberMatchStringSimilarityScorer
  - _target_: kazu.utils.link_index.DictionaryIndex
    parser: ${ontology_parser.cellosaurus_parser}
    boolean_scorers:
      - _target_: kazu.modelling.language.string_similarity_scorers.NumberMatchStringSimilarityScorer
  - _target_: kazu.utils.link_index.DictionaryIndex
    parser: ${ontology_parser.go_bp_parser}
    boolean_scorers:
      - _target_: kazu.modelling.language.string_similarity_scorers.NumberMatchStringSimilarityScorer
  - _target_: kazu.utils.link_index.DictionaryIndex
    parser: ${ontology_parser.go_cc_parser}
    boolean_scorers:
      - _target_: kazu.modelling.language.string_similarity_scorers.NumberMatchStringSimilarityScorer
  - _target_: kazu.utils.link_index.DictionaryIndex
    parser: ${ontology_parser.go_mf_parser}
    boolean_scorers:
      - _target_: kazu.modelling.language.string_similarity_scorers.NumberMatchStringSimilarityScorer
