_target_: kazu.steps.linking.dictionary.DictionaryEntityLinkingStep
depends_on: ~
lookup_cache_size: 50000
top_n: 20
entity_class_to_ontology_mappings:
  drug:
    - CHEMBL
    - OPENTARGETS_MOLECULE
  disease:
    - MEDDRA
    - MONDO
    - OPENTARGETS_DISEASE
  gene:
    - OPENTARGETS_TARGET
  anatomy:
    - UBERON
  cell_line:
    - CELLOSAURUS
  cell_type:
    - CLO
  go_bp:
    - BP_GENE_ONTOLOGY
  go_mf:
    - MF_GENE_ONTOLOGY
  go_cc:
    - CC_GENE_ONTOLOGY
indices:
  - _target_: kazu.utils.link_index.DictionaryIndex
    parser:
      _target_: kazu.modelling.ontology_preprocessing.base.ChemblOntologyParser
      in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/chembl_29_sqlite/chembl_29.db
      data_origin: 'chembl_29_sqlite'
  - _target_: kazu.utils.link_index.DictionaryIndex
    parser:
      _target_: kazu.modelling.ontology_preprocessing.base.MondoOntologyParser
      in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/mondo.json
      data_origin: 'MONDO-2022-04-04'
  - _target_: kazu.utils.link_index.DictionaryIndex
    parser:
      _target_: kazu.modelling.ontology_preprocessing.base.OpenTargetsDiseaseOntologyParser
      in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/opentargets/diseases
      data_origin: 'OPENTARGETS-DISEASE'
  - _target_: kazu.utils.link_index.DictionaryIndex
    parser:
      _target_: kazu.modelling.ontology_preprocessing.base.OpenTargetsMoleculeOntologyParser
      in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/opentargets/molecule
      data_origin: 'OPENTARGETS-MOLECULE'
  - _target_: kazu.utils.link_index.DictionaryIndex
    parser:
      _target_: kazu.modelling.ontology_preprocessing.base.OpenTargetsTargetOntologyParser
      in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/opentargets/targets
      data_origin: 'OPENTARGETS-TARGET'
  - _target_: kazu.utils.link_index.DictionaryIndex
    parser:
      _target_: kazu.modelling.ontology_preprocessing.base.MeddraOntologyParser
      in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/MedDRA 24.1
      data_origin: 'MEDDRA-24.1'
  - _target_: kazu.utils.link_index.DictionaryIndex
    parser:
      _target_: kazu.modelling.ontology_preprocessing.base.UberonOntologyParser
      in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/uberon.owl
      data_origin: 'UBERON'
  - _target_: kazu.utils.link_index.DictionaryIndex
    parser:
      _target_: kazu.modelling.ontology_preprocessing.base.CellosaurusOntologyParser
      in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/cellosaurus.obo
      data_origin: 'CELLOSAURUS'
  - _target_: kazu.utils.link_index.DictionaryIndex
    parser:
      _target_: kazu.modelling.ontology_preprocessing.base.CLOOntologyParser
      in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/clo.owl
      data_origin: 'CLO'
  - _target_: kazu.utils.link_index.DictionaryIndex
    parser:
      _target_: kazu.modelling.ontology_preprocessing.base.BiologicalProcessGeneOntologyParser
      in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/go.owl
      data_origin: 'GO-BP'
  - _target_: kazu.utils.link_index.DictionaryIndex
    parser:
      _target_: kazu.modelling.ontology_preprocessing.base.MolecularFunctionGeneOntologyParser
      in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/go.owl
      data_origin: 'GO-MF'
  - _target_: kazu.utils.link_index.DictionaryIndex
    parser:
      _target_: kazu.modelling.ontology_preprocessing.base.CellularComponentGeneOntologyParser
      in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/go.owl
      data_origin: 'GO-CC'
