_target_: kazu.steps.linking.dictionary.DictionaryEntityLinkingStep
lookup_cache_size: 50000
top_n: 20
skip_ner_namespaces:
  - _target_: kazu.steps.joint_ner_and_linking.explosion.ExplosionStringMatchingStep.namespace
indices: ${oc.dict.values:indices}
