indices:
  cellosaurus_index:
    _target_: kazu.utils.link_index.DictionaryIndex
    parser: ${ontologies.parsers.cellosaurus_parser}
    boolean_scorers: ${StringScorers.number_match_only}
parsers:
  cellosaurus_parser:
    _target_: kazu.ontology_preprocessing.parsers.CellosaurusOntologyParser
    name: CELLOSAURUS
    in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/cellosaurus.obo
    data_origin: '47.0'
    string_scorer: ${SapbertStringSimilarityScorer}
    entity_class: cell_line
    curations_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/${.name}_curations.json
    global_actions: ${global_actions}
    autocurator:
      _target_: kazu.ontology_preprocessing.autocuration.AutoCurator
      actions:
        - _target_: kazu.ontology_preprocessing.autocuration.SymbolicToCaseSensitiveAction
          entity_class: ${ontologies.parsers.cellosaurus_parser.entity_class}
        - _target_: kazu.ontology_preprocessing.autocuration.IsCommmonWord
          path: ${oc.env:KAZU_MODEL_PACK}/misc/20k_most_common.txt
        - _target_: kazu.ontology_preprocessing.autocuration.MinLength
          min_len: 2
        - _target_: kazu.ontology_preprocessing.autocuration.MaxLength
          max_len: 60
        - _target_: hydra.utils.get_method
          path: kazu.ontology_preprocessing.autocuration.reverse_camel_case_to_case_sensitive
