indices:
  chembl_index:
    _target_: kazu.utils.link_index.DictionaryIndex
    parser: ${ontologies.parsers.chembl_parser}
    boolean_scorers: ${StringScorers.drug}
parsers:
  chembl_parser:
    _target_: kazu.ontology_preprocessing.parsers.ChemblOntologyParser
    in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/chembl_33/chembl_33_sqlite/chembl_33.db
    data_origin: '33'
    name: CHEMBL
    string_scorer: ${SapbertStringSimilarityScorer}
    synonym_generator: ${SynonymGeneration.chemical}
    entity_class: drug
    curations_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/${.name}_curations.json
    global_actions: ${global_actions}
