indices:
  chembl_index:
    _target_: kazu.utils.link_index.DictionaryIndex
    parser: ${ontologies.parsers.chembl_parser}
    boolean_scorers: ${StringScorers.number_match_only}
parsers:
  chembl_parser:
    _target_: kazu.ontology_preprocessing.parsers.ChemblParquetOntologyParser
    in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/chembl_34_subset.parquet
    data_origin: '34'
    name: CHEMBL
    string_scorer: ${SapbertStringSimilarityScorer}
    synonym_generator: ${SynonymGeneration.chemical}
    entity_class: drug
    curations_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/${.name}_curations.jsonl
    global_actions: ${global_actions}
    autocurator: ${autocurator.chembl}
    ontology_downloader:
      _target_: kazu.ontology_preprocessing.downloads.ChemblParquetOntologyDownloader
      chembl_version: ${..data_origin}
