indices:
  cl_index:
    _target_: kazu.utils.link_index.DictionaryIndex
    parser: ${ontologies.parsers.cl_parser}
    boolean_scorers: ${StringScorers.number_match_only}
parsers:
  cl_parser:
    _target_: kazu.ontology_preprocessing.parsers.CLOntologyParser
    name: CL
    in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/cl.owl
    data_origin: '2024-05-15'
    string_scorer: ${SapbertStringSimilarityScorer}
    synonym_generator: ${SynonymGeneration.default}
    entity_class: cell_type
    curations_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/${.name}_curations.jsonl
    global_actions: ${global_actions}
    autocurator: ${autocurator.cell_line_or_type}
    ontology_downloader:
      _target_: kazu.ontology_preprocessing.downloads.OwlOntologyDownloader
      url: http://purl.obolibrary.org/obo/cl.owl
