indices:
  clo_index:
    _target_: kazu.utils.link_index.DictionaryIndex
    parser: ${ontologies.parsers.clo_parser}
    boolean_scorers: ${StringScorers.number_match_only}
parsers:
  clo_parser:
    _target_: kazu.ontology_preprocessing.parsers.CLOOntologyParser
    name: CLO
    in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/clo.owl
    data_origin: '2.1.188'
    string_scorer: ${SapbertStringSimilarityScorer}
    entity_class: cell_line
    curations_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/${.name}_curations.jsonl
    global_actions: ${global_actions}
    autocurator: ${autocurator.cell_line_or_type}
    ontology_downloader:
      _target_: kazu.ontology_preprocessing.downloads.OwlOntologyDownloader
      url: http://purl.obolibrary.org/obo/clo.owl
