indices:
  clo_index:
    _target_: kazu.utils.link_index.DictionaryIndex
    parser: ${ontologies.parsers.clo_parser}
    boolean_scorers: ${StringScorers.cell_line}
parsers:
  clo_parser:
    _target_: kazu.modelling.ontology_preprocessing.parsers.CLOOntologyParser
    name: CLO
    in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/clo.owl
    data_origin: CLO
    string_scorer: ${SapbertStringSimilarityScorer}
    entity_class: cell_type
    curations_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/${.name}_curations.json
    global_actions: ${global_actions}
