indices:
  go_cc_index:
    _target_: kazu.utils.link_index.DictionaryIndex
    parser: ${ontologies.parsers.go_cc_parser}
    boolean_scorers: ${StringScorers.number_match_only}
parsers:
  go_cc_parser:
    _target_: kazu.ontology_preprocessing.parsers.CellularComponentGeneOntologyParser
    name: CC_GENE_ONTOLOGY
    in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/go.owl
    data_origin: '2023-10-09'
    string_scorer: ${SapbertStringSimilarityScorer}
    synonym_generator: ${SynonymGeneration.default}
    entity_class: cellular_component
    curations_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/${.name}_curations.json
    global_actions: ${global_actions}
    autocurator:
      _target_: kazu.ontology_preprocessing.autocuration.AutoCurator
      actions:
        - _target_: kazu.ontology_preprocessing.autocuration.SymbolicToCaseSensitiveAction
          entity_class: ${ontologies.parsers.go_cc_parser.entity_class}
        - _target_: kazu.ontology_preprocessing.autocuration.IsCommmonWord
          path: ${oc.env:KAZU_MODEL_PACK}/misc/20k_most_common.txt
        - _target_: kazu.ontology_preprocessing.autocuration.MinLength
          min_len: 2
        - _target_: kazu.ontology_preprocessing.autocuration.MaxLength
          max_len: 60
        - _target_: hydra.utils.get_method
          path: kazu.ontology_preprocessing.autocuration.reverse_camel_case_to_case_sensitive
