indices:
  go_mf_index:
    _target_: kazu.utils.link_index.DictionaryIndex
    parser: ${ontologies.parsers.go_mf_parser}
    boolean_scorers: ${StringScorers.number_match_only}
parsers:
  go_mf_parser:
    _target_: kazu.ontology_preprocessing.parsers.MolecularFunctionGeneOntologyParser
    name: MF_GENE_ONTOLOGY
    in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/go.owl
    data_origin: '2024-06-17'
    string_scorer: ${SapbertStringSimilarityScorer}
    synonym_generator: ${SynonymGeneration.default}
    entity_class: molecular_function
    curations_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/${.name}_curations.jsonl
    global_actions: ${global_actions}
    autocurator: ${autocurator.basic}
    ontology_downloader:
      _target_: kazu.ontology_preprocessing.downloads.OwlOntologyDownloader
      url: http://purl.obolibrary.org/obo/go.owl
