indices:
  hgnc_gene_family_index:
    _target_: kazu.utils.link_index.DictionaryIndex
    parser: ${ontologies.parsers.hgnc_gene_family_parser}
    boolean_scorers: ${StringScorers.gene}
parsers:
  hgnc_gene_family_parser:
    _target_: kazu.ontology_preprocessing.parsers.HGNCGeneFamilyParser
    name: HGNC_GENE_FAMILY
    in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/gene_family.tsv
    data_origin: 'HGNC Mart 31.10.23'
    string_scorer: ${SapbertStringSimilarityScorer}
    synonym_generator: ${SynonymGeneration.gene}
    entity_class: gene
    curations_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/${.name}_curations.jsonl
    global_actions: ${global_actions}
    autocurator:
      _target_: kazu.ontology_preprocessing.autocuration.AutoCurator
      actions:
        - _target_: kazu.ontology_preprocessing.autocuration.SymbolicToCaseSensitiveAction
          entity_class: ${ontologies.parsers.hgnc_gene_family_parser.entity_class}
        - _target_: kazu.ontology_preprocessing.autocuration.IsCommmonWord
          path: ${oc.env:KAZU_MODEL_PACK}/misc/20k_most_common.txt
        - _target_: kazu.ontology_preprocessing.autocuration.MinLength
          min_len: 2
        - _target_: kazu.ontology_preprocessing.autocuration.MaxLength
          max_len: 60
        - _target_: hydra.utils.get_method
          path: kazu.ontology_preprocessing.autocuration.initial_lowercase_then_upper_to_case_sensitive
