indices:
  hpo_index:
    _target_: kazu.utils.link_index.DictionaryIndex
    parser: ${ontologies.parsers.hpo_parser}
    boolean_scorers: ${StringScorers.disease}
parsers:
  hpo_parser:
    _target_: kazu.ontology_preprocessing.parsers.HPOntologyParser
    name: HPO_PHENOTYPE_ABNORMALITY
    in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/hp-full.owl
    data_origin: '2023-10-09'
    string_scorer: ${SapbertStringSimilarityScorer}
    synonym_generator: ${SynonymGeneration.default}
    entity_class: disease
    curations_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/${.name}_curations.jsonl
    global_actions: ${global_actions}
    uri_regex: "^http://purl.obolibrary.org/obo/HP_[0-9]+$"
    synonym_predicates:
      - 'http://www.geneontology.org/formats/oboInOwl#hasExactSynonym'
    include_entity_patterns:
      - - _target_: rdflib.paths.MulPath
          path:
            _target_: rdflib.URIRef
            value: 'http://www.w3.org/2000/01/rdf-schema#subClassOf'
          mod: '+'
        - 'http://purl.obolibrary.org/obo/HP_0000118'
    autocurator:
      _target_: kazu.ontology_preprocessing.autocuration.AutoCurator
      actions:
        - _target_: kazu.ontology_preprocessing.autocuration.SymbolicToCaseSensitiveAction
          entity_class: ${ontologies.parsers.hpo_parser.entity_class}
        - _target_: kazu.ontology_preprocessing.autocuration.LikelyAcronym
        - _target_: kazu.ontology_preprocessing.autocuration.IsCommmonWord
          path: ${oc.env:KAZU_MODEL_PACK}/misc/20k_most_common.txt
        - _target_: kazu.ontology_preprocessing.autocuration.MinLength
          min_len: 2
        - _target_: kazu.ontology_preprocessing.autocuration.MaxLength
          max_len: 60
        - _target_: hydra.utils.get_method
          path: kazu.ontology_preprocessing.autocuration.initial_lowercase_then_upper_to_case_sensitive
