indices:
  mondo_index:
    _target_: kazu.utils.link_index.DictionaryIndex
    parser: ${ontologies.parsers.mondo_parser}
    boolean_scorers: ${StringScorers.disease}
parsers:
  mondo_parser:
    _target_: kazu.ontology_preprocessing.parsers.MondoOntologyParser
    name: MONDO
    in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/mondo.json
    data_origin: 'MONDO-v2023-05-01'
    string_scorer: ${SapbertStringSimilarityScorer}
    synonym_generator: ${SynonymGeneration.default}
    entity_class: disease
    curations_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/${.name}_curations.json
    global_actions: ${global_actions}
