indices:
  ot_bio_proc_index:
    _target_: kazu.utils.link_index.DictionaryIndex
    parser: ${ontologies.parsers.ot_bio_proc_parser}
    boolean_scorers: ${StringScorers.number_match_only}
parsers:
  ot_bio_proc_parser:
    name: OPENTARGETS_BIOLOGICAL_PROC
    _target_: kazu.ontology_preprocessing.parsers.OpenTargetsDiseaseOntologyParser
    in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/opentargets/diseases
    data_origin: '24.06'
    string_scorer: ${SapbertStringSimilarityScorer}
    synonym_generator: ${SynonymGeneration.default}
    entity_class: biological_process
    curations_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/${.name}_curations.jsonl
    global_actions: ${global_actions}
    allowed_therapeutic_areas:
      - 'GO_0008150'
    autocurator: ${autocurator.basic}
    ontology_downloader:
      _target_: kazu.ontology_preprocessing.downloads.OpenTargetsOntologyDownloader
      open_targets_version: ${..data_origin}
      open_targets_dataset_name: diseases
