indices:
  ot_disease_index:
    _target_: kazu.utils.link_index.DictionaryIndex
    parser: ${ontologies.parsers.ot_disease_parser}
    boolean_scorers: ${StringScorers.disease}
parsers:
  ot_disease_parser:
    name: OPENTARGETS_DISEASE
    _target_: kazu.ontology_preprocessing.parsers.OpenTargetsDiseaseOntologyParser
    in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/opentargets/diseases
    data_origin: '23.09'
    string_scorer: ${SapbertStringSimilarityScorer}
    synonym_generator: ${SynonymGeneration.default}
    entity_class: disease
    curations_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/${.name}_curations.jsonl
    global_actions: ${global_actions}
    allowed_therapeutic_areas:
      - 'MONDO_0024458'
      - 'OTAR_0000006'
      - 'MONDO_0002025'
      - 'EFO_0001379'
      - 'EFO_0009690'
      - 'EFO_0000540'
      - 'EFO_0005741'
      - 'EFO_0000319'
      - 'EFO_0009605'
      - 'MONDO_0045024'
      - 'OTAR_0000018'
      - 'OTAR_0000020'
      - 'EFO_0010285'
      - 'OTAR_0000010'
      - 'EFO_0005803'
      - 'EFO_0005932'
      - 'OTAR_0000009'
      - 'MONDO_0021205'
      - 'OTAR_0000017'
      - 'EFO_0010282'
      - 'OTAR_0000014'
      - 'EFO_0000618'
    autocurator:
      _target_: kazu.ontology_preprocessing.autocuration.AutoCurator
      actions:
        - _target_: kazu.ontology_preprocessing.autocuration.SymbolicToCaseSensitiveAction
          entity_class: ${ontologies.parsers.ot_disease_parser.entity_class}
        - _target_: kazu.ontology_preprocessing.autocuration.LikelyAcronym
        - _target_: kazu.ontology_preprocessing.autocuration.IsCommmonWord
          path: ${oc.env:KAZU_MODEL_PACK}/misc/20k_most_common.txt
        - _target_: kazu.ontology_preprocessing.autocuration.MinLength
          min_len: 2
        - _target_: kazu.ontology_preprocessing.autocuration.MaxLength
          max_len: 60
        - _target_: hydra.utils.get_method
          path: kazu.ontology_preprocessing.autocuration.initial_lowercase_then_upper_to_case_sensitive
