indices:
  ot_molecule_index:
    _target_: kazu.utils.link_index.DictionaryIndex
    parser: ${ontologies.parsers.ot_molecule_parser}
    boolean_scorers: ${StringScorers.number_match_only}
parsers:
  ot_molecule_parser:
    _target_: kazu.ontology_preprocessing.parsers.OpenTargetsMoleculeOntologyParser
    name: OPENTARGETS_MOLECULE
    in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/opentargets/molecule
    data_origin: '24.06'
    string_scorer: ${SapbertStringSimilarityScorer}
    synonym_generator: ${SynonymGeneration.chemical}
    entity_class: drug
    curations_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/${.name}_curations.jsonl
    global_actions: ${global_actions}
    autocurator: ${autocurator.chembl}
    ontology_downloader:
      _target_: kazu.ontology_preprocessing.downloads.OpenTargetsOntologyDownloader
      open_targets_version: ${..data_origin}
      open_targets_dataset_name: molecule
