indices:
  ot_target_index:
    _target_: kazu.utils.link_index.DictionaryIndex
    parser: ${ontologies.parsers.ot_target_parser}
    boolean_scorers: ${StringScorers.gene}
parsers:
  ot_target_parser:
    _target_: kazu.ontology_preprocessing.parsers.OpenTargetsTargetOntologyParser
    name: OPENTARGETS_TARGET
    in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/opentargets/targets
    data_origin: '23.09'
    string_scorer: ${SapbertStringSimilarityScorer}
    synonym_generator: ${SynonymGeneration.gene}
    entity_class: gene
    curations_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/${.name}_curations.json
    global_actions: ${global_actions}
    excluded_biotypes:
      - "Mt_rRNA"
      - "Mt_tRNA"
      - "misc_RNA"
      - "rRNA"
      - "scRNA"
      - "snRNA"
      - "snoRNA"
      - "ribozyme"
      - "sRNA"
      - "scaRNA"
      - "TEC"
      - ""
    autocurator:
      _target_: kazu.ontology_preprocessing.autocuration.AutoCurator
      actions:
        - _target_: kazu.ontology_preprocessing.autocuration.SymbolicToCaseSensitiveAction
          entity_class: ${ontologies.parsers.ot_target_parser.entity_class}
        - _target_: kazu.ontology_preprocessing.autocuration.IsCommmonWord
          path: ${oc.env:KAZU_MODEL_PACK}/misc/20k_most_common.txt
        - _target_: kazu.ontology_preprocessing.autocuration.MinLength
          min_len: 2
        - _target_: kazu.ontology_preprocessing.autocuration.MaxLength
          max_len: 60
        - _target_: hydra.utils.get_method
          path: kazu.ontology_preprocessing.autocuration.reverse_camel_case_to_case_sensitive
