indices:
  stato_index:
    _target_: kazu.utils.link_index.DictionaryIndex
    parser: ${ontologies.parsers.stato_parser}
    # we can just reuse the anatomy scorer here, rather than defining a new type
    boolean_scorers: ${StringScorers.anatomy}
parsers:
  stato_parser:
    _target_: kazu.ontology_preprocessing.parsers.StatoParser
    name: STATO
    in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/stato.owl
    data_origin: 'RC1.4'
    string_scorer: ${SapbertStringSimilarityScorer}
    synonym_generator: ${SynonymGeneration.default}
    entity_class: measurement
    curations_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/${.name}_curations.json
    global_actions: ${global_actions}
