indices:
  uberon_index:
    _target_: kazu.utils.link_index.DictionaryIndex
    parser: ${ontologies.parsers.uberon_parser}
    boolean_scorers: ${StringScorers.number_match_only}
parsers:
  uberon_parser:
    _target_: kazu.ontology_preprocessing.parsers.UberonOntologyParser
    name: UBERON
    in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/uberon.owl
    data_origin: '2023-09-05'
    string_scorer: ${SapbertStringSimilarityScorer}
    synonym_generator: ${SynonymGeneration.default}
    entity_class: anatomy
    curations_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/${.name}_curations.json
    global_actions: ${global_actions}
    autocurator:
      _target_: kazu.ontology_preprocessing.autocuration.AutoCurator
      actions:
        - _target_: kazu.ontology_preprocessing.autocuration.SymbolicToCaseSensitiveAction
          entity_class: ${ontologies.parsers.uberon_parser.entity_class}
        - _target_: kazu.ontology_preprocessing.autocuration.IsCommmonWord
          path: ${oc.env:KAZU_MODEL_PACK}/misc/20k_most_common.txt
        - _target_: kazu.ontology_preprocessing.autocuration.MinLength
          min_len: 2
        - _target_: kazu.ontology_preprocessing.autocuration.MaxLength
          max_len: 60
        - _target_: hydra.utils.get_method
          path: kazu.ontology_preprocessing.autocuration.initial_lowercase_then_upper_to_case_sensitive
