indices:
  uberon_index:
    _target_: kazu.utils.link_index.DictionaryIndex
    parser: ${ontologies.parsers.uberon_parser}
    boolean_scorers: ${StringScorers.number_match_only}
parsers:
  uberon_parser:
    _target_: kazu.ontology_preprocessing.parsers.UberonOntologyParser
    name: UBERON
    in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/uberon.owl
    data_origin: 'http://purl.obolibrary.org/obo/uberon/releases/2024-05-13/uberon.owl'
    string_scorer: ${SapbertStringSimilarityScorer}
    synonym_generator: ${SynonymGeneration.default}
    entity_class: anatomy
    curations_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/${.name}_curations.jsonl
    global_actions: ${global_actions}
    autocurator: ${autocurator.basic}
    ontology_downloader:
      _target_: kazu.ontology_preprocessing.downloads.OwlOntologyDownloader
      url: http://purl.obolibrary.org/obo/uberon.owl
