indices:
  uberon_index:
    _target_: kazu.utils.link_index.DictionaryIndex
    parser: ${ontologies.parsers.uberon_parser}
    boolean_scorers: ${StringScorers.anatomy}
parsers:
  uberon_parser:
    _target_: kazu.ontology_preprocessing.parsers.UberonOntologyParser
    name: UBERON
    in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/uberon.owl
    data_origin: 'UBERON-2022-09-30'
    string_scorer: ${SapbertStringSimilarityScorer}
    synonym_generator: ${SynonymGeneration.default}
    entity_class: anatomy
    curations_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/${.name}_curations.json
    global_actions: ${global_actions}
