_target_: azner.steps.linking.dictionary.DictionaryEntityLinkingStep
depends_on: ~
lookup_cache_size: 5000
fuzzy: True
top_n: 20
score_cutoff: 90.0
index_group:
  _target_: azner.utils.caching.CachedIndexGroup
  entity_class_to_ontology_mappings:
    drug:
      - CHEMBL
    disease:
      - MONDO
      - MEDDRA
    gene:
      - ENSEMBL
    anatomy:
      - UBERON
    species:
      - NOT_IMPLEMENTED
    mutation:
      - NOT_IMPLEMENTED
  cache_managers:
    - _target_: azner.utils.caching.DictionaryIndexCacheManager
      rebuild_cache: True
      index_type: DictionaryIndex
      parsers:
        - _target_: azner.modelling.ontology_preprocessing.base.ChemblOntologyParser
          in_path: ???
        - _target_: azner.modelling.ontology_preprocessing.base.EnsemblOntologyParser
          in_path: ???
        - _target_: azner.modelling.ontology_preprocessing.base.MondoOntologyParser
          in_path: ???
        - _target_: azner.modelling.ontology_preprocessing.base.UberonOntologyParser
          in_path: ???
        - _target_: azner.modelling.ontology_preprocessing.base.MeddraOntologyParser
          in_path: ???
        - _target_: azner.modelling.ontology_preprocessing.base.CLOOntologyParser
          in_path: ???
        - _target_: azner.modelling.ontology_preprocessing.base.CellosaurusOntologyParser
          in_path: ???