_target_: kazu.steps.ner.hf_token_classification.TransformersModelForTokenClassificationNerStep
path: ${oc.env:KAZU_MODEL_PACK}/tinybern
depends_on: ~
batch_size: 4
stride: 16
max_sequence_length: 128
trainer:
  _target_: pytorch_lightning.Trainer
  progress_bar_refresh_rate: 0
  gpus: 0
  logger: false
entity_splitter:
  _target_: kazu.steps.ner.entity_post_processing.NonContiguousEntitySplitter
  entity_conditions:
    gene:
      - _target_: kazu.steps.ner.entity_post_processing.SplitOnNumericalListPatternWithPrefix
      - _target_: kazu.steps.ner.entity_post_processing.SplitOnConjunctionPattern
        spacy_model: en_core_sci_md
    disease:
      - _target_: kazu.steps.ner.entity_post_processing.SplitOnConjunctionPattern
        spacy_model: en_core_sci_md
