_target_: kazu.steps.ner.hf_token_classification.TransformersModelForTokenClassificationNerStep
path: ${oc.env:KAZU_MODEL_PACK}/tinybern
batch_size: 4
stride: 16
max_sequence_length: 128
entity_splitter:
  _target_: kazu.steps.ner.entity_post_processing.NonContiguousEntitySplitter
  entity_conditions:
    gene:
      - _target_: kazu.steps.ner.entity_post_processing.SplitOnNumericalListPatternWithPrefix
      - _target_: kazu.steps.ner.entity_post_processing.SplitOnConjunctionPattern
        path: ${SciSpacyPipeline.path}
    disease:
      - _target_: kazu.steps.ner.entity_post_processing.SplitOnConjunctionPattern
        path: ${SciSpacyPipeline.path}
detect_subspans: False
threshold: ~
labels:
  - 'B-cell_line'
  - 'B-cell_type'
  - 'B-disease'
  - 'B-drug'
  - 'B-gene'
  - 'B-species'
  - 'I-cell_line'
  - 'I-cell_type'
  - 'I-disease'
  - 'I-drug'
  - 'I-gene'
  - 'I-species'
  - 'O'
strip_re:
  gene: "( (gene|protein)s?)+$"
