_target_: kazu.steps.ner.seth.SethStep
entity_class: mutation
seth_fatjar_path: ${oc.env:KAZU_MODEL_PACK}/kazu-jvm/kazu-jvm-1.0-fatjar.jar
java_home: ${oc.env:JAVA_HOME}
condition:
  _target_: kazu.utils.utils.EntityClassFilter
  required_entity_classes:
    - gene
