_target_: kazu.steps.other.entity_dedup.NerDeDuplicationStep
namespace_preferred_order:
  - _target_: kazu.steps.ner.hf_token_classification.TransformersModelForTokenClassificationNerStep.namespace
  - _target_: kazu.steps.ner.spacy_ner.SpacyNerStep.namespace
  - _target_: kazu.steps.joint_ner_and_linking.explosion.ExplosionStringMatchingStep.namespace
