_target_: kazu.steps.other.document_disambiguation.DocumentLevelDisambiguationStep
depends_on: ~ddi
tfidf_disambiguator:
  _target_: kazu.steps.other.document_disambiguationv2.Disambiguator
  path: ${oc.env:KAZU_MODEL_PACK}/disambiguation/tfidf_vec.pkl
