MappingFilterCleanupAction:
  _target_: kazu.steps.other.cleanup.MappingFilterCleanupAction
  filter_fns:
    - _target_: kazu.steps.other.cleanup.DropMappingsByConfidenceMappingFilter
      disambiguation_ranks_to_drop:
        - _target_: kazu.data.DisambiguationConfidence
          _args_:
            - AMBIGUOUS
      string_match_ranks_to_drop:
        _target_: builtins.list
EntityFilterCleanupAction:
  _target_: kazu.steps.other.cleanup.EntityFilterCleanupAction
  filter_fns:
    - _target_: kazu.steps.other.cleanup.DropUnmappedEntityFilter
      from_ent_namespaces: ~
