EntityFilterCleanupAction:
  _target_: kazu.steps.other.cleanup.EntityFilterCleanupAction
  filter_fns:
    - _target_: kazu.steps.other.cleanup.DropUnmappedEntityFilter
      from_ent_namespaces:
        - _target_: kazu.steps.ner.explosion.ExplosionNERStep.namespace
MappingFilterCleanupAction:
  _target_: kazu.steps.other.cleanup.MappingFilterCleanupAction
  filter_fns:
    - _target_: kazu.steps.other.cleanup.DropMappingsByConfidenceMappingFilter
      ranks_to_drop:
        - _target_: kazu.data.data.LinkRanks
          _args_:
            - AMBIGUOUS
