EntityFilterCleanupAction:
  _target_: kazu.steps.other.cleanup.EntityFilterCleanupAction
  filter_fns:
    - _target_: kazu.steps.other.cleanup.DropUnmappedEntityFilter
      from_ent_namespaces:
        - _target_: kazu.steps.ner.explosion.ExplosionNERStep.namespace
