EntityFilterCleanupAction:
  _target_: kazu.steps.other.cleanup.EntityFilterCleanupAction.from_filter_fn_providers
  filter_providers:
    - _target_: kazu.steps.other.cleanup.DropUnmappedEntsEntityFilters
      from_ent_namespaces:
        - _target_: kazu.steps.ner.explosion.ExplosionNERStep.namespace
