DiseaseBlackLister:
  _target_: kazu.modelling.ontology_matching.blacklist.synonym_blacklisting.DiseaseBlackLister
  annotation_lookup:
    _target_: kazu.modelling.ontology_matching.blacklist.synonym_blacklisting.AnnotationLookup
    annotations_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/curations/disease_kazu_ExplosionNERStep_unique_ner_agg.csv
  disease_synonym_sources:
    - OPENTARGETS_DISEASE
DrugBlackLister:
  _target_: kazu.modelling.ontology_matching.blacklist.synonym_blacklisting.DrugBlackLister
  annotation_lookup:
    _target_: kazu.modelling.ontology_matching.blacklist.synonym_blacklisting.AnnotationLookup
    annotations_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/curations/drug_kazu_ExplosionNERStep_unique_ner_agg.csv
  anatomy_synonym_sources:
    - UBERON
  gene_synonym_sources:
    - OPENTARGETS_TARGET
GeneBlackLister:
  _target_: kazu.modelling.ontology_matching.blacklist.synonym_blacklisting.GeneBlackLister
  annotation_lookup:
    _target_: kazu.modelling.ontology_matching.blacklist.synonym_blacklisting.AnnotationLookup
    annotations_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/curations/gene_kazu_ExplosionNERStep_unique_ner_agg.csv
  disease_synonym_sources:
    - OPENTARGETS_DISEASE
  gene_synonym_sources:
    - OPENTARGETS_TARGET
