cellosaurus_parser:
  _target_: kazu.modelling.ontology_preprocessing.parsers.CellosaurusOntologyParser
  name: "CELLOSAURUS"
  in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/cellosaurus.obo
  data_origin: 'CELLOSAURUS'
  string_scorer: ${SapbertStringSimilarityScorer}
  entity_class: 'cell_line'
  curations: ${curations}
  global_actions: ${global_actions}
