chembl_parser:
  _target_: kazu.modelling.ontology_preprocessing.base.ChemblOntologyParser
  in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/chembl_31_sqlite/chembl_31.db
  data_origin: 'chembl_31_sqlite'
  name: "CHEMBL"
  string_scorer: ${SapbertStringSimilarityScorer}
  synonym_generator: ${SynonymGeneration.chemical}
  entity_class: 'drug'
  curations: ${curations}
  global_actions: ${global_actions}
