cl_parser:
  _target_: kazu.modelling.ontology_preprocessing.base.CLOntologyParser
  name: "CL"
  in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/cl.owl
  data_origin: 'CL'
  string_scorer: ${SapbertStringSimilarityScorer}
  synonym_generator: ${SynonymGeneration.default}
  entity_class: 'cell_type'
  curations:
    _target_: kazu.modelling.ontology_preprocessing.base.load_curated_terms
    path: ${oc.env:KAZU_MODEL_PACK}/curations/curations.json
  global_actions:
    _target_: kazu.modelling.ontology_preprocessing.base.load_global_actions
    path: ${oc.env:KAZU_MODEL_PACK}/curations/global_parser_actions.json
