clo_parser:
  _target_: kazu.modelling.ontology_preprocessing.base.CLOOntologyParser
  name: "CLO"
  in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/clo.owl
  data_origin: 'CLO'
  string_scorer: ${SapbertStringSimilarityScorer}
  entity_class: 'cell_type'
  curations:
    _target_: kazu.modelling.ontology_preprocessing.base.load_curated_terms
    path: ${oc.env:KAZU_MODEL_PACK}/curations.json
