chembl_parser:
  _target_: kazu.modelling.ontology_preprocessing.base.ChemblOntologyParser
  in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/chembl_29_sqlite/chembl_29.db
  data_origin: 'chembl_29_sqlite'
  spacy_pipeline: ${SpacyPipeline}
  synonym_generator: ${SynonymGeneration.chemical}

mondo_parser:
  _target_: kazu.modelling.ontology_preprocessing.base.MondoOntologyParser
  in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/mondo.json
  data_origin: 'MONDO-2022-07-29'
  spacy_pipeline: ${SpacyPipeline}
  synonym_generator: ${SynonymGeneration.default}

ot_disease_parser:
  _target_: kazu.modelling.ontology_preprocessing.base.OpenTargetsDiseaseOntologyParser
  in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/opentargets/diseases
  data_origin: 'OPENTARGETS-DISEASE'
  spacy_pipeline: ${SpacyPipeline}
  synonym_generator: ${SynonymGeneration.default}

ot_molecule_parser:
  _target_: kazu.modelling.ontology_preprocessing.base.OpenTargetsMoleculeOntologyParser
  in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/opentargets/molecule
  data_origin: 'OPENTARGETS-MOLECULE'
  spacy_pipeline: ${SpacyPipeline}
  synonym_generator: ${SynonymGeneration.chemical}

ot_target_parser:
  _target_: kazu.modelling.ontology_preprocessing.base.OpenTargetsTargetOntologyParser
  in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/opentargets/targets
  data_origin: 'OPENTARGETS-TARGET'
  spacy_pipeline: ${SpacyPipeline}
  synonym_generator: ${SynonymGeneration.gene}
  symbol_classifier:
    _target_: kazu.modelling.language.symbol_classification.GeneSymbolClassifier

meddra_parser:
  _target_: kazu.modelling.ontology_preprocessing.base.MeddraOntologyParser
  in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/MedDRA 24.1
  data_origin: 'MEDDRA-24.1'
  spacy_pipeline: ${SpacyPipeline}
  synonym_generator: ${SynonymGeneration.default}

uberon_parser:
  _target_: kazu.modelling.ontology_preprocessing.base.UberonOntologyParser
  in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/uberon.owl
  data_origin: 'UBERON'
  spacy_pipeline: ${SpacyPipeline}
  synonym_generator: ${SynonymGeneration.default}

cellosaurus_parser:
  _target_: kazu.modelling.ontology_preprocessing.base.CellosaurusOntologyParser
  in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/cellosaurus.obo
  data_origin: 'CELLOSAURUS'
  spacy_pipeline: ${SpacyPipeline}

clo_parser:
  _target_: kazu.modelling.ontology_preprocessing.base.CLOOntologyParser
  in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/clo.owl
  data_origin: 'CLO'
  spacy_pipeline: ${SpacyPipeline}

go_bp_parser:
  _target_: kazu.modelling.ontology_preprocessing.base.BiologicalProcessGeneOntologyParser
  in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/go.owl
  data_origin: 'GO-BP'
  spacy_pipeline: ${SpacyPipeline}
  synonym_generator: ${SynonymGeneration.default}

go_mf_parser:
  _target_: kazu.modelling.ontology_preprocessing.base.MolecularFunctionGeneOntologyParser
  in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/go.owl
  data_origin: 'GO-MF'
  spacy_pipeline: ${SpacyPipeline}
  synonym_generator: ${SynonymGeneration.default}

go_cc_parser:
  _target_: kazu.modelling.ontology_preprocessing.base.CellularComponentGeneOntologyParser
  in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/go.owl
  data_origin: 'GO-CC'
  spacy_pipeline: ${SpacyPipeline}
  synonym_generator: ${SynonymGeneration.default}
