go_bp_parser:
  _target_: kazu.modelling.ontology_preprocessing.base.BiologicalProcessGeneOntologyParser
  name: "BP_GENE_ONTOLOGY"
  in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/go.owl
  data_origin: 'GO-BP'
  string_scorer: ${SapbertStringSimilarityScorer}
  synonym_generator: ${SynonymGeneration.default}
  entity_class: 'go_bp'
  curations:
    _target_: kazu.modelling.ontology_preprocessing.base.load_curated_terms
    path: ${oc.env:KAZU_MODEL_PACK}/curations.json
