go_cc_parser:
  _target_: kazu.modelling.ontology_preprocessing.parsers.CellularComponentGeneOntologyParser
  name: "CC_GENE_ONTOLOGY"
  in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/go.owl
  data_origin: 'GO-CC'
  string_scorer: ${SapbertStringSimilarityScorer}
  synonym_generator: ${SynonymGeneration.default}
  entity_class: 'go_cc'
  curations: ${curations}
  global_actions: ${global_actions}
