ot_disease_parser:
  name: "OPENTARGETS_DISEASE"
  _target_: kazu.modelling.ontology_preprocessing.base.OpenTargetsDiseaseOntologyParser
  in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/opentargets/disease
  data_origin: 'OPENTARGETS-DISEASE'
  string_scorer: ${SapbertStringSimilarityScorer}
  synonym_generator: ${SynonymGeneration.default}
  entity_class: 'disease'
  curations: ${curations}
  global_actions: ${global_actions}
