ot_target_parser:
  _target_: kazu.modelling.ontology_preprocessing.parsers.OpenTargetsTargetOntologyParser
  name: "OPENTARGETS_TARGET"
  in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/opentargets/targets
  data_origin: 'OPENTARGETS-TARGET'
  string_scorer: ${SapbertStringSimilarityScorer}
  synonym_generator: ${SynonymGeneration.gene}
  entity_class: 'gene'
  curations: ${curations}
  global_actions: ${global_actions}
