uberon_parser:
  _target_: kazu.modelling.ontology_preprocessing.base.UberonOntologyParser
  name: "UBERON"
  in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/uberon.owl
  data_origin: 'UBERON'
  string_scorer: ${SapbertStringSimilarityScorer}
  synonym_generator: ${SynonymGeneration.default}
  entity_class: 'anatomy'
  curations:
    _target_: kazu.modelling.ontology_preprocessing.base.load_curated_terms
    path: ${oc.env:KAZU_MODEL_PACK}/curations.json
