uberon_parser:
  _target_: kazu.modelling.ontology_preprocessing.base.UberonOntologyParser
  name: "UBERON"
  in_path: ${oc.env:KAZU_MODEL_PACK}/ontologies/uberon.owl
  data_origin: 'UBERON'
  string_scorer: ${SapbertStringSimilarityScorer}
  synonym_generator: ${SynonymGeneration.default}
  entity_class: 'anatomy'
  curations: ${curations}
  global_actions: ${global_actions}
