_target_: kazu.steps.linking.mapping_step.MappingStep
depends_on: ~
strategy_runner:
  _target_: kazu.steps.linking.post_processing.strategy_runner.StrategyRunner
  cross_ref_manager:
    _target_: kazu.steps.linking.post_processing.xref_manager.CrossReferenceManager
    source_to_parser_metadata_lookup:
      MEDDRA: MEDDRA_DISEASE
      MONDO: MONDO
      HP: OPENTARGETS_DISEASE
    path:
      _target_: pathlib.Path
      _args_:
        - ${oc.env:KAZU_MODEL_PACK}/mapping_step/oxo_dump
  ner_namespace_processing_order:
    - TransformersModelForTokenClassificationNerStep
    - ExplosionNERStep
  symbolic_strategies:

    TransformersModelForTokenClassificationNerStep:
      _target_: kazu.steps.linking.post_processing.strategy_runner.NamespaceStrategyExecution
      stop_on_success: True
      default_strategies:
        - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.ExactMatchMappingStrategy
          confidence: HIGHLY_LIKELY
          disambiguation_strategies: ${DisambiguationStrategies.default}

        - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.SymbolMatchMappingStrategy
          confidence: PROBABLE
          disambiguation_strategies: ${DisambiguationStrategies.default}

        - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.TermNormIsSubStringMappingStrategy
          confidence: PROBABLE
          disambiguation_strategies: ${DisambiguationStrategies.default}

        - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.StrongMatchMappingStrategy
          confidence: POSSIBLE
          disambiguation_strategies: ${DisambiguationStrategies.default}
          symbolic_only: True
      ent_class_strategies:
        gene:
          - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.ExactMatchMappingStrategy
            confidence: HIGHLY_LIKELY
            disambiguation_strategies: ${DisambiguationStrategies.gene}

          - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.SymbolMatchMappingStrategy
            confidence: PROBABLE
            disambiguation_strategies: ${DisambiguationStrategies.gene}

          - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.TermNormIsSubStringMappingStrategy
            confidence: PROBABLE
            disambiguation_strategies: ${DisambiguationStrategies.gene}

          - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.StrongMatchMappingStrategy
            confidence: POSSIBLE
            disambiguation_strategies: ${DisambiguationStrategies.gene}
            symbolic_only: True
            search_threshold: 90.0
        disease:
          - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.ExactMatchMappingStrategy
            confidence: HIGHLY_LIKELY
            disambiguation_strategies: ${DisambiguationStrategies.default}

          - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.SymbolMatchMappingStrategy
            confidence: PROBABLE
            disambiguation_strategies: ${DisambiguationStrategies.default}

          - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.TermNormIsSubStringMappingStrategy
            confidence: PROBABLE
            disambiguation_strategies: ${DisambiguationStrategies.gene}

          - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.StrongMatchMappingStrategy
            confidence: POSSIBLE
            disambiguation_strategies: ${DisambiguationStrategies.default}
            symbolic_only: True
        cell_line:
          - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.ExactMatchMappingStrategy
            confidence: HIGHLY_LIKELY
            disambiguation_strategies: ${DisambiguationStrategies.cell_line}

          - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.SymbolMatchMappingStrategy
            confidence: PROBABLE
            disambiguation_strategies: ${DisambiguationStrategies.cell_line}

          - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.TermNormIsSubStringMappingStrategy
            confidence: PROBABLE
            disambiguation_strategies: ${DisambiguationStrategies.cell_line}

    ExplosionNERStep:
      _target_: kazu.steps.linking.post_processing.strategy_runner.NamespaceStrategyExecution
      stop_on_success: True
      default_strategies:
        - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.DefinedElsewhereInDocumentMappingStrategy
          confidence: HIGHLY_LIKELY
          disambiguation_strategies:
            - _target_: kazu.steps.linking.post_processing.disambiguation.strategies.DefinedElsewhereInDocumentDisambiguationStrategy
      ent_class_strategies:
        _target_: builtins.dict


  non_symbolic_strategies:

    TransformersModelForTokenClassificationNerStep:
      _target_: kazu.steps.linking.post_processing.strategy_runner.NamespaceStrategyExecution
      stop_on_success: True
      default_strategies:
        - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.ExactMatchMappingStrategy
          confidence: HIGHLY_LIKELY
          disambiguation_strategies: ${DisambiguationStrategies.default}

        - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.StrongMatchMappingStrategy
          confidence: POSSIBLE
          disambiguation_strategies: ${DisambiguationStrategies.default}
          symbolic_only: False
      ent_class_strategies:
        gene:
          - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.ExactMatchMappingStrategy
            confidence: HIGHLY_LIKELY
            disambiguation_strategies: ${DisambiguationStrategies.gene}

          - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.TermNormIsSubStringMappingStrategy
            confidence: PROBABLE
            disambiguation_strategies: ${DisambiguationStrategies.gene}

          - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.StrongMatchMappingStrategy
            confidence: PROBABLE
            disambiguation_strategies: ${DisambiguationStrategies.gene}
            symbolic_only: False
        disease:
          - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.ExactMatchMappingStrategy
            confidence: HIGHLY_LIKELY
            disambiguation_strategies: ${DisambiguationStrategies.default}

          - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.StrongMatchWithEmbeddingConfirmationStringMatchingStrategy
            confidence: POSSIBLE
            disambiguation_strategies: ${DisambiguationStrategies.default}
            symbolic_only: False
            complex_string_scorer:
              _target_: kazu.modelling.language.string_similarity_scorers.SapbertStringSimilarityScorer
              sapbert: ${PLSapbertModel}
              trainer:
                _target_: pytorch_lightning.Trainer
                enable_progress_bar: False
                accelerator: "cpu"
                logger: False
          - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.ExactMatchMappingStrategy
            confidence: HIGHLY_LIKELY
            disambiguation_strategies: ${DisambiguationStrategies.cell_line}

          - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.SymbolMatchMappingStrategy
            confidence: PROBABLE
            disambiguation_strategies: ${DisambiguationStrategies.cell_line}

          - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.TermNormIsSubStringMappingStrategy
            confidence: PROBABLE
            disambiguation_strategies: ${DisambiguationStrategies.cell_line}
    ExplosionNERStep:
      _target_: kazu.steps.linking.post_processing.strategy_runner.NamespaceStrategyExecution
      stop_on_success: True
      default_strategies:
        - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.DefinedElsewhereInDocumentMappingStrategy
          disambiguation_strategies:
            - _target_: kazu.steps.linking.post_processing.disambiguation.strategies.DefinedElsewhereInDocumentDisambiguationStrategy
          confidence: HIGHLY_LIKELY
      ent_class_strategies:
        anatomy:
          - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.ExactMatchMappingStrategy
            disambiguation_strategies:
              - _target_: kazu.steps.linking.post_processing.disambiguation.strategies.DefinedElsewhereInDocumentDisambiguationStrategy
            confidence: HIGHLY_LIKELY
        go_bp:
          - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.ExactMatchMappingStrategy
            disambiguation_strategies:
              - _target_: kazu.steps.linking.post_processing.disambiguation.strategies.DefinedElsewhereInDocumentDisambiguationStrategy
            confidence: HIGHLY_LIKELY
        go_cc:
          - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.ExactMatchMappingStrategy
            disambiguation_strategies:
              - _target_: kazu.steps.linking.post_processing.disambiguation.strategies.DefinedElsewhereInDocumentDisambiguationStrategy
            confidence: HIGHLY_LIKELY
        go_mf:
          - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.ExactMatchMappingStrategy
            disambiguation_strategies:
              - _target_: kazu.steps.linking.post_processing.disambiguation.strategies.DefinedElsewhereInDocumentDisambiguationStrategy
            confidence: HIGHLY_LIKELY
        disease:
          - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.ExactMatchMappingStrategy
            confidence: HIGHLY_LIKELY
            disambiguation_strategies: ${DisambiguationStrategies.default}

          - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.StrongMatchWithEmbeddingConfirmationStringMatchingStrategy
            confidence: PROBABLE
            disambiguation_strategies: ${DisambiguationStrategies.default}
            symbolic_only: False
            complex_string_scorer:
              _target_: kazu.modelling.language.string_similarity_scorers.SapbertStringSimilarityScorer
              sapbert: ${PLSapbertModel}
              trainer:
                _target_: pytorch_lightning.Trainer
                enable_progress_bar: False
                accelerator: "cpu"
                logger: False
        drug:
          - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.ExactMatchMappingStrategy
            confidence: PROBABLE
            disambiguation_strategies: ${DisambiguationStrategies.default}
