_target_: kazu.steps.linking.mapping_step.MappingStep
parsers: ${oc.dict.values:ontologies.parsers}
strategy_runner:
  _target_: kazu.steps.linking.post_processing.strategy_runner.StrategyRunner
  cross_ref_managers: ~
  symbolic_strategies:

    HIGHLY_LIKELY:
      _target_: kazu.steps.linking.post_processing.strategy_runner.ConfidenceLevelStrategyExecution
      stop_on_success: True
      default_strategies:
        - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.ExactMatchMappingStrategy
          confidence: ${confidence.string_matching_highly_likely}
          disambiguation_strategies: ${DisambiguationStrategies.default}

        - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.SymbolMatchMappingStrategy
          confidence: ${confidence.string_matching_probable}
          disambiguation_strategies: ${DisambiguationStrategies.default}

        - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.TermNormIsSubStringMappingStrategy
          confidence: ${confidence.string_matching_probable}
          disambiguation_strategies: ${DisambiguationStrategies.default}

        - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.StrongMatchMappingStrategy
          confidence: ${confidence.string_matching_possible}
          disambiguation_strategies: ${DisambiguationStrategies.default}
          symbolic_only: True
      ent_class_strategies:
        gene:
          - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.ExactMatchMappingStrategy
            confidence: ${confidence.string_matching_highly_likely}
            disambiguation_strategies: ${DisambiguationStrategies.gene}

          - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.SymbolMatchMappingStrategy
            confidence: ${confidence.string_matching_probable}
            disambiguation_strategies: ${DisambiguationStrategies.gene}

          - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.TermNormIsSubStringMappingStrategy
            confidence: ${confidence.string_matching_probable}
            disambiguation_strategies: ${DisambiguationStrategies.gene}

          - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.StrongMatchMappingStrategy
            confidence: ${confidence.string_matching_possible}
            disambiguation_strategies: ${DisambiguationStrategies.gene}
            symbolic_only: True
            search_threshold: 90.0
        disease:
          - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.ExactMatchMappingStrategy
            confidence: ${confidence.string_matching_highly_likely}
            disambiguation_strategies: ${DisambiguationStrategies.default}

          - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.SymbolMatchMappingStrategy
            confidence: ${confidence.string_matching_probable}
            disambiguation_strategies: ${DisambiguationStrategies.default}

          - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.TermNormIsSubStringMappingStrategy
            confidence: ${confidence.string_matching_probable}
            disambiguation_strategies: ${DisambiguationStrategies.gene}

          - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.StrongMatchMappingStrategy
            confidence: ${confidence.string_matching_possible}
            disambiguation_strategies: ${DisambiguationStrategies.default}
            symbolic_only: True
        drug:
          - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.ExactMatchMappingStrategy
            confidence: ${confidence.string_matching_highly_likely}
            disambiguation_strategies: ${DisambiguationStrategies.default}
        cell_line:
          - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.ExactMatchMappingStrategy
            confidence: ${confidence.string_matching_highly_likely}
            disambiguation_strategies: ${DisambiguationStrategies.cell_line}

          - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.SymbolMatchMappingStrategy
            confidence: ${confidence.string_matching_probable}
            disambiguation_strategies: ${DisambiguationStrategies.cell_line}

          - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.TermNormIsSubStringMappingStrategy
            confidence: ${confidence.string_matching_probable}
            disambiguation_strategies: ${DisambiguationStrategies.cell_line}

    PROBABLE:
      _target_: kazu.steps.linking.post_processing.strategy_runner.ConfidenceLevelStrategyExecution
      stop_on_success: True
      default_strategies:
        - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.NoopMappingStrategy
          confidence: ${confidence.string_matching_highly_likely}
          disambiguation_strategies:
            - _target_: kazu.steps.linking.post_processing.disambiguation.strategies.DefinedElsewhereInDocumentDisambiguationStrategy
              confidence: ${confidence.disambiguation_highly_likely}
      ent_class_strategies:
        _target_: builtins.dict

    POSSIBLE:
      _target_: kazu.steps.linking.post_processing.strategy_runner.ConfidenceLevelStrategyExecution
      stop_on_success: True
      default_strategies:
        - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.NoopMappingStrategy
          confidence: ${confidence.string_matching_highly_likely}
          disambiguation_strategies:
            - _target_: kazu.steps.linking.post_processing.disambiguation.strategies.DefinedElsewhereInDocumentDisambiguationStrategy
              confidence: ${confidence.disambiguation_highly_likely}
      ent_class_strategies:
        _target_: builtins.dict


  non_symbolic_strategies:

    HIGHLY_LIKELY:
      _target_: kazu.steps.linking.post_processing.strategy_runner.ConfidenceLevelStrategyExecution
      stop_on_success: True
      default_strategies:
        - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.ExactMatchMappingStrategy
          confidence: ${confidence.string_matching_highly_likely}
          disambiguation_strategies: ${DisambiguationStrategies.default}

        - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.StrongMatchMappingStrategy
          confidence: ${confidence.string_matching_possible}
          disambiguation_strategies: ${DisambiguationStrategies.default}
          symbolic_only: False
      ent_class_strategies:
        drug:
          - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.ExactMatchMappingStrategy
            confidence: ${confidence.string_matching_highly_likely}
            disambiguation_strategies: ${DisambiguationStrategies.default}
        gene:
          - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.ExactMatchMappingStrategy
            confidence: ${confidence.string_matching_highly_likely}
            disambiguation_strategies: ${DisambiguationStrategies.gene}

          - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.TermNormIsSubStringMappingStrategy
            confidence: ${confidence.string_matching_probable}
            disambiguation_strategies: ${DisambiguationStrategies.gene}

          - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.StrongMatchMappingStrategy
            confidence: ${confidence.string_matching_probable}
            disambiguation_strategies: ${DisambiguationStrategies.gene}
            symbolic_only: False
        disease:
          - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.ExactMatchMappingStrategy
            confidence: ${confidence.string_matching_highly_likely}
            disambiguation_strategies: ${DisambiguationStrategies.default}

          - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.StrongMatchWithEmbeddingConfirmationStringMatchingStrategy
            confidence: ${confidence.string_matching_possible}
            disambiguation_strategies: ${DisambiguationStrategies.default}
            symbolic_only: False
            complex_string_scorer: ${SapbertStringSimilarityScorer}
        cell_line:
          - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.ExactMatchMappingStrategy
            confidence: ${confidence.string_matching_highly_likely}
            disambiguation_strategies: ${DisambiguationStrategies.cell_line}

          - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.SymbolMatchMappingStrategy
            confidence: ${confidence.string_matching_probable}
            disambiguation_strategies: ${DisambiguationStrategies.cell_line}

          - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.TermNormIsSubStringMappingStrategy
            confidence: ${confidence.string_matching_probable}
            disambiguation_strategies: ${DisambiguationStrategies.cell_line}
    PROBABLE:
      _target_: kazu.steps.linking.post_processing.strategy_runner.ConfidenceLevelStrategyExecution
      stop_on_success: True
      default_strategies:
        - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.ExactMatchMappingStrategy
          disambiguation_strategies: ${DisambiguationStrategies.default}
          confidence: ${confidence.string_matching_highly_likely}
      ent_class_strategies:
        # we don't expect any value from the disambiguation strategies for these ontologies, so save the effort
        anatomy:
          - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.ExactMatchMappingStrategy
            disambiguation_strategies: ~
            confidence: ${confidence.string_matching_highly_likely}
        go_bp:
          - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.ExactMatchMappingStrategy
            disambiguation_strategies: ~
            confidence: ${confidence.string_matching_highly_likely}
        go_cc:
          - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.ExactMatchMappingStrategy
            disambiguation_strategies: ~
            confidence: ${confidence.string_matching_highly_likely}
        go_mf:
          - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.ExactMatchMappingStrategy
            disambiguation_strategies: ~
            confidence: ${confidence.string_matching_highly_likely}
        cell_line:
          - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.ExactMatchMappingStrategy
            disambiguation_strategies: ~
            confidence: ${confidence.string_matching_highly_likely}
        cell_type:
          - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.ExactMatchMappingStrategy
            disambiguation_strategies: ~
            confidence: ${confidence.string_matching_highly_likely}

    POSSIBLE:
      _target_: kazu.steps.linking.post_processing.strategy_runner.ConfidenceLevelStrategyExecution
      stop_on_success: True
      default_strategies:
        - _target_: kazu.steps.linking.post_processing.mapping_strategies.strategies.NoopMappingStrategy
          confidence: ${confidence.string_matching_highly_likely}
          disambiguation_strategies:
            - _target_: kazu.steps.linking.post_processing.disambiguation.strategies.DefinedElsewhereInDocumentDisambiguationStrategy
              confidence: ${confidence.disambiguation_highly_likely}
      ent_class_strategies:
        _target_: builtins.dict
