default:
  _target_: kazu.modelling.ontology_preprocessing.synonym_generation.CombinatorialSynonymGenerator
  synonym_generators:
    - _target_: kazu.modelling.ontology_preprocessing.synonym_generation.StopWordRemover
      spacy_pipeline: ${SpacyPipeline}
    - _target_: kazu.modelling.ontology_preprocessing.synonym_generation.CaseModifier
      lower: true
      upper: true
      title: true
    - _target_: kazu.modelling.ontology_preprocessing.synonym_generation.StringReplacement
      replacement_dict:
        "-":
          - " "
          - "_"
        "_":
          - " "
          - "-"
      digit_aware_replacement_dict:
        " ":
          - "-"
      include_greek: true
gene:
  _target_: kazu.modelling.ontology_preprocessing.synonym_generation.CombinatorialSynonymGenerator
  synonym_generators:
    - _target_: kazu.modelling.ontology_preprocessing.synonym_generation.CaseModifier
      lower: true
      upper: true
      title: true
    - _target_: kazu.modelling.ontology_preprocessing.synonym_generation.SeparatorExpansion
      spacy_pipeline: ${SpacyPipeline}
    - _target_: kazu.modelling.ontology_preprocessing.synonym_generation.StringReplacement
      replacement_dict:
        "-":
          - " "
          - "_"
        "_":
          - " "
          - "-"
      digit_aware_replacement_dict:
        " ":
          - "-"
      include_greek: true
chemical:
  _target_: kazu.modelling.ontology_preprocessing.synonym_generation.CombinatorialSynonymGenerator
  synonym_generators:
    - _target_: kazu.modelling.ontology_preprocessing.synonym_generation.CaseModifier
      lower: true
      upper: true
      title: true
    - _target_: kazu.modelling.ontology_preprocessing.synonym_generation.StringReplacement
      include_greek: true
