name: Build and push the latest build to staging

on:
  push:
    tags:
      - 'v*'

jobs:
  build_push_image:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Fetch latest version
        id: fetch_version
        run: echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.CONTAINER_REGISTERY_NAME }}
          username: ${{ secrets.CONTAINER_REGISTERY_LOGIN }}
          password: ${{ secrets.CONTAINER_REGISTERY_PASSWORD }}

      - name: Build and push staging images
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ${{secrets.CONTAINER_REGISTERY_NAME}}/azner:latest,${{secrets.CONTAINER_REGISTERY_NAME}}/azner:${{ steps.fetch_version.outputs.TAG }}
          push: true
  deploy:
    runs-on: ubuntu-latest
    needs: build_push_image
    steps:
      - uses: actions/checkout@v2

      - name: Fetch latest version
        id: fetch_version
        run: echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}

      - name: Install Helm
        uses: Azure/setup-helm@v1
        with:
          version: v3.7.0

      - name: Get AKS creds
        uses: Azure/aks-set-context@v1.1
        with:
          # Azure credentials i.e. output of `az ad sp create-for-rbac --sdk-auth`
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}
      - name: Run Helm Deploy
        run: |
          helm  \
          upgrade \
          --atomic \
          --wait \
          --wait-for-jobs \
          -n ray \
          --install ray-cluster \
          --create-namespace \
          --set dns.name=${{ secrets.DNS_NAME }}  \
          --set image=${{secrets.CONTAINER_REGISTERY_NAME}}/azner:${{ steps.fetch_version.outputs.TAG }} \
          ./kubernetes/ray
