name: Integration tests

on:
  pull_request_review:
    branches: [ main ]
    types: [submitted]

  workflow_dispatch:

jobs:
  model-pack-tests:
    if: github.event.review.state == 'approved' || github.event_name == 'workflow_dispatch'
    runs-on: [self-hosted, has-model-pack]
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.9" ]
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ hashFiles('setup.py') }}

      - name: create venv and install dependencies
        run: |
          rm -r kazu-env || true
          
          PIP_CACHE_DIR=$(pip cache dir)
          echo "pip cache dir is "${PIP_CACHE_DIR}
          python -m venv /tmp/kazu-env
          . /tmp/kazu-env/bin/activate
          python -m pip install --upgrade pip
          pip install -e ."[dev,webserver]"  --cache-dir $PIP_CACHE_DIR


      - name: Check precommit
        run: |
          . /tmp/kazu-env/bin/activate
          pre-commit run --all-files

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup and execute Gradle 'test' task
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
          build-root-directory: kazu-jvm/

      - name: Run Sphinx doctest
        run: |
          make -C docs doctest          

      - name: Build model pack caches and test
        id: model_pack_cache_build
        run: |
          export BASE_KAZU_CONF_PATH=$GITHUB_WORKSPACE"/kazu/conf"
          # random suffix to prevent clashes with other runs          
          export MODEL_PACK_BUILD_PATH=$GITHUB_WORKSPACE"/temp_model_pack_test_dir_"$RANDOM
     
          mkdir $MODEL_PACK_BUILD_PATH   
          
          . /tmp/kazu-env/bin/activate
          
          python -m kazu.utils.build_and_test_model_packs \
          --base_model_pack_path $DEFAULT_MODEL_PACK_PATH \
          --base_configuration_path $BASE_KAZU_CONF_PATH \
          --model_packs_to_build \
          $DEFAULT_MODEL_PACK_PATH \
          --model_pack_output_path $MODEL_PACK_BUILD_PATH \
          --skip_tests
          
          export KAZU_MODEL_PACK=$(echo $MODEL_PACK_BUILD_PATH/kazu_model_pack_public)
          
          pytest
          
          # need to call twice, for NFS bug
          rm -r /tmp/kazu-env || true
          rm -r /tmp/kazu-env || true
          
          rm -r $MODEL_PACK_BUILD_PATH || true
          rm -r $MODEL_PACK_BUILD_PATH || true
        env:
          DEFAULT_MODEL_PACK_PATH: /home/github/runner/.kazu_data/kazu_model_pack_public
          TOKENIZERS_PARALLELISM: false
          PL_DISABLE_FORK: 1
