name: Integration tests

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      model-pack-path:
        description: Path in the github runner VM's filesystem to find the model pack for this test run. If not set, the test runner will search for the a suitable model pack
        required: false
      model-packs-dir:
        description: Path to where model packs are stored on the VM's filesystem
        required: true
        default: /home/github/runner/.kazu_data

jobs:
  model-pack-tests:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.9" ]
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # This step outputs a model pack path to be used in the pytest below.
      # If defined, it will simply output the model_pack_path input argument.
      # Otherwise, it will run  latest_model_pack_path.py to find a suitable model_pack_{git commit hash} on
      # the runner by examining the git commit log.
      - name: Set model_pack path
        id: get_model_pack
        run: |
          if [ -z "$model_pack_path"]
          then
            output=$(python3 .github/workflows/latest_model_pack_path.py ${{ env.model_packs_dir }})
            echo "::set-output name=model_pack_path::$output"
          else
            echo "::set-output name=model_pack_path::$model_pack_path"
          fi
        env:
          model_pack_path: ${{ inputs.model-pack-path }}
          model_packs_dir: ${{ inputs.model-packs-dir }}


      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ hashFiles('setup.py') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Check precommit
        run: |
          pre-commit run --all-files

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      # Runs the tests and sets a model pack so @require_model_pack tests will also be run
      # Note that these tests won't build caches as part of their operation and will likely
      # re-use existing cached data.
      - name: Test with pytest
        run: |
          pytest
        env:
          KAZU_MODEL_PACK: ${{ steps.get_model_pack.outputs.model_pack_path }}
          TOKENIZERS_PARALLELISM: false
          PL_DISABLE_FORK: 1
