name: Temporary Deployment
on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: git ref
        required: true
      release-version:
        description: version of release for model pack
        required: true
      kazu-version:
        description: version of release for kazu
        required: true
      seconds:
        description: time to keep deployment alive in seconds
        required: true
      
jobs:
  build:
    runs-on: [self-hosted, az-ai-runners]
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with: 
          ref: ${{inputs.git-ref}}
      
      - name: download release
        shell: bash
        run: |
         gh release download --repo=https://github.com/AZ-AI/kazu/ ${{inputs.release-version}} --dir deploy
        env:
         GH_TOKEN: ${{ github.token }}

      - name: Build
        uses: az-ai/az-action-registry@v4.1.1
        with:
          registry: ${{vars.REGISTRY}}
          username: ${{secrets.HARBOR_USERNAME}}
          password: ${{secrets.HARBOR_PASSWORD}}
          image-name: nlp/kazu/temp-kazu-dev
          build-args: |
            BASE_IMAGE=${{vars.REGISTRY}}/bc-sai-test/python-amd:3.9
            ARTIFACTORY_USER=${{secrets.ARTIFACT_USERNAME}}
            ARTIFACTORY_TOKEN=${{secrets.ARTIFACT_TOKEN}}
            MODEL_PACK_PATH=deploy/kazu_model_pack_public-${{inputs.release-version}}.zip
            KAZU_PACKAGE=.
            KAZU_VERSION=${{inputs.kazu-version}}
            DEPLOYMENT=temporary
          build-context: .
          dockerfile-name: deploy/temporary/Dockerfile
          tags: temp-${{inputs.git-ref}}
          use-proxies: 'true'
          needs-sudo: 'true'

      - name: Clean up
        shell: bash
        run: |
          rm -rf deploy/kazu_model_pack*
  
  deploy-temp:
    name: "Deploy image to K8s Dev cluster"
    runs-on: [self-hosted, kazu-runners]
    needs: build
    steps:
      - name: deploy to dev
        uses: az-ai/az-action-k8s-deploy-rest-api@0.10.0
        with:
          kube_config: ${{secrets.KUBE_CONFIG}}
          project_name: temporary-kazu
          ingress_name: temporary-kazu
          image:  ${{vars.REGISTRY}}/nlp/kazu/temp-kazu-dev:temp-${{inputs.git-ref}}
          docker_registry: ${{vars.REGISTRY}}
          docker_username: ${{secrets.HARBOR_USERNAME}}
          docker_password: ${{secrets.HARBOR_PASSWORD}}
          namespace: kazu-test
          host_url: ${{vars.AZ_URL}}
          docker_email: "None"
          external_port: 80
          internal_port: 8080
          limits_memory: "14Gi"
          requests_memory: "12Gi"
          project_label: nlp
          env_label: test
          env_secrets: |
            KAZU_JWT_KEY=${{secrets.JWT_TOKEN}}
            CORS_ORIGIN_REGEX=https://kazu-ui.${{vars.AZ_URL}}
          replicas: 1
          enable_autoscaling: "yes"
          max_replicas: 2
          target_cpu_utilisation: 80
          wait: 300
          organisation: ${{secrets.ORG}}
          rechargeref: ${{secrets.RECHARGE_REF}}
          application_name: nlp-kazu
  
  time-to-live:
    name: Apply time to live to Deployment 
    runs-on: [self-hosted, kazu-runners]
    needs: deploy-temp
    steps:
      - name: ttl for deployment
        uses: az-ai/az-action-ttl-for-k8s-deployment@0.1.0
        with:
          kube_config: ${{secrets.KUBE_CONFIG}}
          namespace: kazu-test
          project_name: temporary-kazu
          seconds: ${{inputs.seconds}}
    
