_target_: kazu.steps.other.cleanup.CleanupStep
cleanup_actions:
  - ${CleanupActions.MappingFilterCleanupAction}
  - ${CleanupActions.EntityFilterCleanupAction}
  - ${CleanupActions.StripMappingURIsAction}
